Malinga/Malinga/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Malinga/blog/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views

app_name = 'blog';

urlpatterns = [
    re_path('home', views.home, name='home'),
    path('category', views.cate, name='category'),
    re_path('blogs', views.blogs, name='blogs'),
    path('post/<int:pk>/', views.blog, name='post'),
    path('post/<int:pk>/',views.BlogView.as_view(), name='post'),
    path('admin2', views.admin, name='admin'),
    
]

Malinga/blog/models.py
from django.db import models


class Tag(models.Model):
	name = models.CharField(max_length=240)

	def __str__(self):
		return self.name

class Category(models.Model):
	name = models.CharField(max_length=255)
	image = models.ImageField(upload_to='category_image', null=True, blank=True)

	def __str__(self):
		return self.name	
		
class Post (models.Model):
	name = models.CharField(max_length=64)
	title = models.CharField(max_length=255)
	body = models.TextField()
	publish_date = models.DateField(auto_now_add=True)
	updated_date = models.DateField(auto_now_add=True)
	image = models.ImageField(upload_to='post_images/', null=True, blank=True)
	tags = models.ManyToManyField(Tag)
	categorys = models.ManyToManyField(Category)
	

	def __str__(self):
		return self.title


class PostImage(models.Model):
	post = models.ForeignKey(Post, default=None, on_delete=models.CASCADE)
	image = models.ImageField(upload_to='post_gallery', null=True, blank=True)		

Malinga/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import *
from django.views.generic import ListView, DetailView

# Create your views here.

def admin(request):
	return render(request, 'admin/index2.html')

def home(request, ):
	post = Post.objects.all()
	object_list = Post.objects.all().order_by('-publish_date')[:3]
	return render(request, 'index.html', {'posts':post, 'object_lists':object_list})


def blogs(request):
	post = Post.objects.all()
	return render(request, 'blogs.html', {'posts':post})


class BlogView(DetailView):
	model = Post
	template = 'blogpost.html'

	def get_success_url(self):
		return self.object.get_absolute_url()

	def get_context_data(self, pk, *args, **kwargs):
		context = super(FrontPageView, self).get_context_data(**kwargs)
		object_list = Post.objects.all().order_by('-publish_date')[:4]
		
		context.update({
			'object_lists':object_list
			})


def blog(request, pk):
	post = get_object_or_404(Post, pk=pk)
	tag = Tag.objects.filter(post=post)
	category = Category.objects.all()
	categories = Category.objects.filter(post=post)
	#similar_posts = self.object.tags.similar_objects()[:2]
	object_list = Post.objects.all().order_by('-publish_date')[:3]
	context = {'post':post,'categorys':category, 'object_lists':object_list, 'tags':tag,
				'categories':categories}
				#'similar_posts':similar_posts}
	return render(request, 'singleblog.html', context)


def cate(request):
	categorys = Category.objects.all()
	
	context = {'categorys':categorys}
	
	
	return render(request,'categories.html', context)

Malinga/blog/templates/blogs.html
{% extends 'main.html' %}
{% load static %}

<!DOCTYPE html>

{% block content %}
<body>

	


		<div class="imge">
			<img src="{% static 'images/blogs/b4.jpg' %}"  class="b1" style=" width:100%; height: 500px; object-fit:cover;" >
			<div class="box-blog">
				<div>Blogs</div>
			</div>
		</div>
		<div class="blogs2">
			{% for post in posts %}
			<div class="cards2">
				<div class="b2">
					<img src="{{post.image.url}}" class="img" style="object-fit: cover;" width="380" height="450">
					<h1 class="capt2">{{post.name}}</h1>
					<div class="likes">
					<span class="#small-box"><i class="fa fa-calendar icon" style="font-size:20px; color:#cc0066;"></i>{{post.publish_date}}</span>
					<hr width="130px" left="150">
					<span class="#small-box"><i class="fa fa-comments icon" style="font-size:20px; color:#cc0066;"></i>41 Comments </span>
					<hr width="130px">
					
					<span class="#small-box"><i class="fa fa-thumbs-up icon" style="font-size:20px; color:#cc0066;"></i>12 Likes </span>
					</div>
				</div>
				
				<div class="text">
					<div class="para-blogs">
						
					<h2>{{post.title}}</h2>					

					<p>{{post.body|truncatewords:43}}</p>
					<a href="{% url 'blog:post' post.pk %}"><button>Read More</button></a>
					</div>	
					
				</div>
				
			</div>
				
				{% endfor %}
		</div>


		<!--start footer-->
	<footer>
		<!--logo-footer-->
		<div class="footer-container">
				
			<div class="logo-parag">
				<div class="logorey">
					<img src="{% static 'images/logo3 2.png' %}"  class="logory">
				</div>
				<div class="logopara" >
				<p > we are located at Mbeya Soweto Road<br>
				Gorofa number 423<br>
				p.o.box 2331 </p>
				</div>
			</div>
			<div class="footer-links">
				<div class="links">
					<a href="#">Interior</a>
					<a href="#"> Nails</a>
					<a href="#"> Fashion</a> 
					<a href="#">Lifestyle</a>
					<a href="#"> Lifestyle</a> 
					<a href="#">Fashion</a> 
					<a href="#">Lifestyle</a> 
					<a href="#">Interior</a>
					<a href="#"> Nails</a>
					<a href="#"> Exterior</a>
				
				</div>
				<div class="copyright" >
					<p>Copyright@MalingaFashion&lifestyle.com</p>
				</div>

			</div>
			<div class="socials">
				<div class="social-footer">
					<i class="fa fa-facebook" style="font-size:30px; color:white;"></i>
					<i class="fa fa-instagram icon" style="font-size:30px; color:white;"></i>
					<i class="fa fa-twitter icon"style="font-size:30px; color:white;"></i>
					<i class="fa fa-pinterest icon" style="font-size:30px; color:white;"></i>
					<i class="ion ion-social-youtube" style="font-size:30px; color:white;"></i>
				</div>
					<div class=" info-social">
					<p>follow us on twitter as Malingas_one,<br>on Facebook as Malinga's_fashion,<br>on Instagram Malinga's-Fashion,<br>on Pinterest at Malingas'fashion & lifestyle,<br> on Youtube Malinga's Fashion & lifestyle.</p>
					<div>
			</div>
			
		</div>
	</footer>
		
</body>
</html>
{% endblock %}

Malinga/blog/templates/categories.html
{% extends 'main.html' %}
{% load static %}

{% block content %}
	<div class="banner">
		<img src="{% static 'images/b1.jpg' %}" style="width:100%; height:500px; object-fit: cover;">
		<span class="span-ban">Categories</span>
	</div>

	<div class="categories">
		
		{% for category in categorys %}
		<div class="cards_category">
			
			<img src="{{category.image.url}}" style="object-fit: cover; border-radius: 20px; width:360px; height:450px; ">
			
			<div class="card_box">
				<span class="card_box1">{{category.name}}</span>
				<span class="card_box2"><i class="ion ion-eye" style="color: #cc0066;font-size:20px;"></i>views</span>	
			</div>
			
		</div>
		
		{% endfor %}
		
	</div>

		<!--start footer-->
	<footer>
		<!--logo-footer-->
		<div class="footer-container">
				
			<div class="logo-parag">
				<div class="logorey">
					<img src="{% static 'images/logo3 2.png' %}" class="logory">
				</div>
				<div class="logopara" >
				<p > we are located at Mbeya Soweto Road<br>
				Gorofa number 423<br>
				p.o.box 2331 </p>
				</div>
			</div>
			<div class="footer-links">
				<div class="links">
					<a href="#">Interior</a>
					<a href="#"> Nails</a>
					<a href="#"> Fashion</a> 
					<a href="#">Lifestyle</a>
					<a href="#"> Lifestyle</a> 
					<a href="#">Fashion</a> 
					<a href="#">Lifestyle</a> 
					<a href="#">Interior</a>
					<a href="#"> Nails</a>
					<a href="#"> Exterior</a>
				
				</div>
				<div class="copyright" >
					<p>Copyright@MalingaFashion&lifestyle.com</p>
				</div>

			</div>
			<div class="socials">
				<div class="social-footer">
					<i class="fa fa-facebook" style="font-size:30px; color:white;"></i>
					<i class="fa fa-instagram icon" style="font-size:30px; color:white;"></i>
					<i class="fa fa-twitter icon"style="font-size:30px; color:white;"></i>
					<i class="fa fa-pinterest icon" style="font-size:30px; color:white;"></i>
					<i class="ion ion-social-youtube" style="font-size:30px; color:white;"></i>
				</div>
					<div class=" info-social">
					<p>follow us on twitter as Malingas_one,<br>on Facebook as Malinga's_fashion,<br>on Instagram Malinga's-Fashion,<br>on Pinterest at Malingas'fashion & lifestyle,<br> on Youtube Malinga's Fashion & lifestyle.</p>
					<div>
			</div>
			
		</div>
	</footer>

</body>
</html>

{% endblock %}

Malinga/blog/templates/form.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
	<style type="text/css">
		form{
			padding: 30px;
		}
		label{
			margin-bottom: 40px;
		}
		input[type=text]{
			padding: 12px 20px ;
			width: 70%;

		}
	</style>
</head>
<body>
	<form>
		<label>Product_name</label>
		<input type="text" name="product_name">
		
		<lable>Price</lable>
		<input type="text" name="price">
		
		<label>Mfg_date</lable>
		<input type="date" name="mfg_date">
		<label>Exp_date</lable>
		<input type="date" name="exp_date">
		
		<input type="submit" name="submit">
	</form>

</body>
</html>

Malinga/blog/templates/index.html
{% extends 'main.html' %}
{% load static %}


{% block content %}


	
	
	<!--  start of divided image -->
	<div class="content">
		<div class="img-slide">
			<img src="{% static 'images/jumsuit/16.jpg' %}"  class="b1" width="100%" height="600">
			<div class="box">
				<div>Embrace Your own Unique Fashionstyle</div>
			</div>
		</div>
		<div class="img-slide">
			<img src="{% static 'images/jumsuit/15.jpg' %}" class="b1"  width="100%" height="600">
			<div class="box">
				<div>Be the Best version Of Yourself</div>
			</div>
		</div>
	</div>
	<!--  end of divided image -->

	<!--end of navigation bar -->

	<!--cards images-->
	<div class="cards-box">
		<div class="cards">
			<img src="{% static 'images/nails.jpg' %}"  style="object-fit: cover;" class="b2" width="320" height="275">
			<div class="container">
				<h1>Nails</h1>
			</div>
		</div>
		<div class="cards">
			<img src="{% static 'images/interior.jpg' %}"  style="object-fit: cover;" class="b2" width="320" height="275">
			<div class="container">
				<h1>Interior</h1>
			</div>
		</div>
		<div class="cards">
			<img src="{% static 'images/make-up.jpg' %}"  style="object-fit: cover;" class="b2" width="320" height="275">
			<div class="container">
				<h1>Make-up</h1>
			</div>
		</div>
	</div>
	<!--end of images cards-->

	<!--sign up form-->
	<div class="newsletter">
		<div class="heading">Get the latest fashion trends in your inbox</div>
		<form class="news">
			<input type="email" class="email_news" placeholder="Your Email address">
			<input type="submit" value="Subscribe" class="submit_news">
		</form>
	</div>
	<!-- popuar videos-->
	<div class="popvid">
			<h1>POPULAR VIDEOS</h1>
		<div class="pop-videos">
			<div class="cards-video">
				<div class="image">
					<img src="{% static 'images/video_pics/v1.jpg' %}" width="250" height="289">
					<div class="box-small">
						
						<span class="small-box1"><i class="ion ion-clock" style="color: white;font-size:18px;"></i>01:00</span>
						<span class="small-box2"><i class="ion ion-eye" style="color: white;font-size:20px;"></i>13,789</span>
					</div>
				</div>

				<div class="text-1">
					<h3 class="caption-1">20 Baby Photoshoot Ideas On Christmas eve</h3>
				</div>	
			</div>
			<div class="cards-video">
				<div class="image">
					<img src="images/video_pics/v2.jpg" width="250" height="289">
					<div class="box-small">
						<span class="small-box1"><i class="ion ion-clock" style="color: white;font-size:18px;"></i>01:47</span>
						<span class="small-box2"><i class="ion ion-eye" style="color: white;font-size:20px;"></i>1,835</span>
					</div>
				</div>
				<div class="text-1">
					<h3 class="caption-1">Nails Design This Valentine Season</h3>
				</div>	
			</div>
			<div class="cards-video">
				<div class="image">
					<img src="images/video_pics/v4.jpg" width="250" height="289">
					<div class="box-small">
						<span class="small-box1"><i class="ion ion-clock icon" style="color: white;font-size:18px;"></i>09:47</span>
						<span class="small-box2"><i class="ion ion-eye" style="color: white;font-size:20px;"></i>7,739</span>
					</div>
				</div>
				<div class="text-1">
					<h3 class="caption-1">Christmass Nails Design ideas 2023</h3>
				</div>		
			</div>

			<div class="cards-video">
				<div class="image">
					<img src="images/video_pics/v6.jpg" width="250" height="289">
					<div class="box-small">
						<span class="small-box1"><i class="ion ion-clock" style="color: white;font-size:18px;"></i>11:00</span>
						<span class="small-box2"><i class="ion ion-eye" style="color: white;font-size:20px;"></i>11,000</span>
					</div>
				</div>
				<div class="text-1">
					<h3 class="caption-1">Interior Design</h3>	
				</div>
			</div>
		</div>
	</div>
	<!--featured videos-->
	<div class="row">
		<div class="col-9">
			<h1>FEATURED VIDEOS</h1>
			<div class="featured-border">
				<span class="cat">FEATURED VIDEOS</span>
				<span class="cat-1">LIPS</span>
				<span class="cat-1">MAKE-UP</span>
				<span class="cat-1">FASHION</span>
				<span class="cat-1">NAIL</span>
			</div>
			<div class="column">
				<div class="bi-video">
					<img src="{% static 'images/video_pics/b2.jpg' %}" style="object-fit: cover;" width="200%" height="600">
					<div class="feature-box1">
						<span><i class="ion ion-play" style="color: white;font-size:15px;"></i>1:00</span>
					</div>
					<div class="feature-box2">
						<a href="https://www.youtube.com"><span><i class="ion ion-play" style="color: white;font-size:25px;"></i></span></a>
					</div>
					<div class="text-big">
						<h3 class="text-big1">Best 20 Valentine Nails Design 2020</h3>
						<div class="date">
						<span>February 9 2022</span>
						</div>
					</div>
				</div>
			</div>
			<div class="column">
				<div class="sub-videos">
					<div class="image-small">
					<img src="{% static 'images/video_pics/15.jpg' %}" width="150" height="180px">
					<div class="feature-box">
						<span><i class="ion ion-play" style="color: white;font-size:15px;"></i>1:00</span>
					</div>
					<div class="sub-text">
						
						<div class="sub-text1">
						Christmas nails 
						</div>
						<div class="date1">
							<span>February 9 2022</span>
						</div>
					</div>
				</div>
				</div>
				
				<div class="sub-videos">
					<div class="image-small">
					<img src="images/video_pics/v5.jpg" width="150" height="180px">
					<div class="feature-box">
						<span><i class="ion ion-play" style="color: white;font-size:15px;"></i>1:00</span>
					</div>
					<div class="sub-text">
						<div class="sub-text1">
							<span>Valentine Gifts </span>
						</div>
						
						<div class="date1">
							<span>February 9 2022</span>
						</div>
					</div>
				</div>
				</div>
				
				<div class="sub-videos">
					<div class="image-small">
					<img src="images/video_pics/v6.jpg" width="150" height="180px">
					<div class="feature-box">
						<span><i class="ion ion-play" style="color: white;font-size:15px;"></i>1:00</span>
					</div>
					<div class="sub-text">
						<div class="sub-text1">
							Home Office Decor
						</div>
						<div class="date1">
							<span >February 9 2022</span>
						</div>
					</div>
				</div>
				</div>
			</div>
		</div>	
	</div>
		<!--side bar 1-->
	<aside>
		<div class="col-ad">
			<div class="ads-image">
				<img src="{% static 'images/ads-03.jpg' %}" style="object-fit: cover;" width="300" height="700">
				<div class="ads-image1"></div>
				<div class="words"><b>Every Day I am trying to bring to you Better content</b>
					</br><span class="fash"><br>concerning fashion and lifetyle</span></div>
				<button class="read">Read More</button>
			</div>
		</div>
	</aside>

		<!--main content -->
	<div class="row">

		<div class="col-9">
			<h1>Blog Posts</h1>
			{% for post in posts%}
			<div class="post-cards">
				
				<div class="b2">
					<img src="{{post.image.url}}"   style="object-fit: cover; height: 400px;" width="350" class="image-post"><a href="" >
					<span class="small-box"><i class="fa fa-calendar icon" style="font-size:20px"></i>{{post.publish_date|date:"M d"}} </span>
							
						</a>
					<h1 class="capt">{{post.name}}</h1>
				</div>
				<div class="text">
					<div class="post-p">
						
					<h2>{{post.title}}</h2>					

					<p>{{post.body|truncatewords:43 }}</p>
					<a href="{% url 'blog:post' post.pk %}"><button>Read More</button></a>
					</div>	
					<div class="faicon">
						<div><hr></div>
						<i class="fa fa-facebook" style="font-size:20px; color:#cc0066;"></i>
						<i class="fa fa-instagram icon" style="font-size:20px; color:#cc0066;"></i>
						<i class="fa fa-twitter icon" style="font-size:20px; color:#cc0066;"></i>
						<i class="fa fa-pinterest icon" style="font-size:20px; color:#cc0066;"></i>
						<i class="ion ion-social-youtube" style="font-size:20px; color:#cc0066;"></i>
						<i class="fa fa-comment icon" style="sfont-size:20px; float:right;color:#cc0066;">20 Comments</i>
						<div><hr></div>
					</div>
				</div>
				
			</div>
			{% endfor %}
		</div>
		<!--sidebar 2-->
		

		<div class="col-3">
			<div class="profile">
			<img src="{% static 'images/ava.jpg' %}"  style="object-fit: cover;" class="image-pro" width="250" height="250">
			<h1> Hello</h1>
				<p>I'm Jessy and this is my creative space.I think that fashion and lifestyle doesn't have to cost a fortune.The most important thing is to enjoy your life and to be happy that's all that matters.I hope you enjoy and you come back often.</p>
				<a href="posts/dressign_table.html"><button class="read1">Read More</button></a>
			</div>

		<!--latest post-->
	

			<div class="latestPost">
				<h1>Latest Posts</h1>
				{% for latest in object_lists %}
				<div class="cards-latest">
					<div class="image-latest">
						<img src="{{latest.image.url}}" style="object-fit: cover; width:250px; height: 300px;" >
						<div class="latest-box">
							
							<span class="box1-latest">{{latest.name}}</span>
							
							<span class="box2-latest"><i class="ion ion-eye" style="color: white;font-size:20px;"></i>1,835</span>
						</div>
					</div>	
				</div>
					
				{% endfor %}

				
			</div>
			<div class="latestPost">
				<h1>Popular Posts</h1>
				{% for latest in object_lists %}
				<div class="cards-latest">
					<div class="image-latest">
						<img src="{{latest.image.url}}" style="object-fit: cover; width:250px; height: 300px;" >
						<div class="latest-box">
							
							<span class="box1-latest">{{latest.name}}</span>
							
							<span class="box2-latest"><i class="ion ion-eye" style="color: white;font-size:20px;"></i>1,835</span>
						</div>
					</div>	
				</div>
					
				{% endfor %}

				
			</div>
		</div>
	</div>

		<!--start footer-->
	<footer>
		<!--logo-footer-->
		<div class="footer-container">
				
			<div class="logo-parag">
				<div class="logorey">
					<img src="{% static 'images/logo3 2.png' %}" class="logory">
				</div>
				<div class="logopara" >
				<p > we are located at Mbeya Soweto Road<br>
				Gorofa number 423<br>
				p.o.box 2331 </p>
				</div>
			</div>
			<div class="footer-links">
				<div class="links">
					<a href="#">Interior</a>
					<a href="#"> Nails</a>
					<a href="#"> Fashion</a> 
					<a href="#">Lifestyle</a>
					<a href="#"> Lifestyle</a> 
					<a href="#">Fashion</a> 
					<a href="#">Lifestyle</a> 
					<a href="#">Interior</a>
					<a href="#"> Nails</a>
					<a href="#"> Exterior</a>
				
				</div>
				<div class="copyright" >
					<p>Copyright@MalingaFashion&lifestyle.com</p>
				</div>

			</div>
			<div class="socials">
				<div class="social-footer">
					<i class="fa fa-facebook" style="font-size:30px; color:white;"></i>
					<i class="fa fa-instagram icon" style="font-size:30px; color:white;"></i>
					<i class="fa fa-twitter icon"style="font-size:30px; color:white;"></i>
					<i class="fa fa-pinterest icon" style="font-size:30px; color:white;"></i>
					<i class="ion ion-social-youtube" style="font-size:30px; color:white;"></i>
				</div>
					<div class=" info-social">
					<p>follow us on twitter as Malingas_one,<br>on Facebook as Malinga's_fashion,<br>on Instagram Malinga's-Fashion,<br>on Pinterest at Malingas'fashion & lifestyle,<br> on Youtube Malinga's Fashion & lifestyle.</p>
					<div>
			</div>
			
		</div>
	</footer>
		
</body>
</html>

{% endblock %}

Malinga/blog/templates/main.html
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<meta name="description" content="Malinga Fashion & Lifestyle Bog">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Malinga Fashion & Lifestyle</title>
	
	 <!-- Favicon -->
  <link rel="icon" href="{% static './images/favicon.ico">
</head>
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
<!--<link rel="stylesheet" type="text/css" href="font-icons/font-awesome/css/font-awesome.min.css">-->
<link rel="stylesheet" type="text/css" href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'ionicons-2.0.1/css/ionicons.min.css' %}">

<body>
<!-- start of header-->
	<div class="header">
		<!--logo-->
		
				<img src="{% static 'images/logo.png' %}" class="logo">
			<!--end of logo-->
			<!--start of navigation bar-->
		<div class="header-right">
			<ul>
				<li><a href="{% url 'blog:home' %}">Home</a></li>
				<li><a href="{% url 'blog:blogs' %}">Blogs</a></li>
				<li class="menu-list"><a href="{% url 'blog:category' %}">Categories</a>
					<ul class="sub-menu">
					<li><a href="">Nails</a></li>
					<li><a href="">Interior</a></li>
					<li><a href="">Exterior</a></li>
					<li><a href="">Fashion</a></li>
					<li><a href="">Lifestyle</a></li>
					</ul>
				</li>
				<li><a href="">Trendings</a></li>
				<li><a href="">About us</a></li>
				<li class="menu-list"><a href="">Sign Up</a>
					<ul class="sub-menu">
					<li><a href="">Register</a></li>
					<li><a href="">Login</a></li>
					<li><a href="">Logout</a></li>
					</ul>
				</li>
				<li><a href="">Contact us</a></li>
				<li><a href=""><i class="ion ion-search" style="font-size:25px;color:white"></i></a></li>
				
			</ul>
		</div>
			
		</div>

{% block content %}

{% endblock %}
<body>

</html>

templates/_base_vue.html
<!DOCTYPE html>
<html lang="">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="icon" href="http://localhost:8080/favicon.ico">
    <title>vue-app</title>
  <script defer src="http://localhost:8080/js/chunk-vendors.js"></script><script defer src="http://localhost:8080/js/app.js"></script></head>
  <body>
    <noscript>
      <strong>We're sorry but vue-app doesn't work properly without JavaScript enabled. Please enable it to continue.</strong>
    </noscript>
    <div id="app"></div>
    <!-- built files will be auto injected -->
  </body>
</html>